# Generated by Django 5.0.4 on 2024-05-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Оплачено'), ('delivered', 'Доставлено'), ('in_route', 'В пути')], default='paid', max_length=20),
        ),
    ]
